# @format

spring:
  datasource:
    url: jdbc:h2:mem:ayush
  h2.console.enabled: true
  jpa:
    show-sql: true
jwt:
  secret_key: gttyvitvuntcutfbcitfctnvtnvvtntvtntyiit
  time_delta: 900000
  cookie_name: token